import os
import sys
# 判断当前文件是否是文件
# print(os.path.isfile(r'D:\Pycharm\Scripts\WEB_LX\字符串练习.py'))
# 判断当前文件是否是目录
# print(os.path.isdir(r'D:\Pycharm\Scripts\WEB_LX'))
# 获取当前目录
# print(os.getcwd())
# 查看当前系统类型
# print(os.name)
# 创建目录
# os.mkdir('fg')
# 删除目录
# os.rmdir('fg')
# 获取文件的绝对路径
# print(os.path.abspath('侠客行.txt'))
# 判断目录是否存在
# print(os.path.exists(r'D:\Pycharm\Scripts\WEB_LX'))
# 从目录中提取文件名
# print(os.path.basename(r'D:\Pycharm\Scripts\WEB_LX\字符串练习.py'))
# 从目录中提取文件路径不包含文件名
# print(os.path.dirname(r'D:\Pycharm\Scripts\WEB_LX\字符串练习.py'))
# 判断是否是路径
# print(os.path.isdir(r'D:\Pycharm\Scripts\WEB_LX\字符串练习.py'))
# 输出文件名
# print(os.path.relpath(r'D:\Pycharm\Scripts\WEB_LX\字符串练习.py'))
# 输出文件的绝对路径
# print(os.path.realpath(__file__))
# 路径切割,返回元组
# print(os.path.split(os.path.realpath(__file__)))
# 路径拼接
# print(os.path.join(os.path.split(os.path.realpath(__file__))[0],'路径拼接.py'))
